### ISSUE TITLE
Iron and gold wont work

### ISSUE THREAD

**Issue by MoosePodcasts** [ScreamingSandals/BedWars#365] opened 2021-09-25 01:14 UTC
#### Describe the bug 

everything works accept when i go in the shop and try to buy anything for iron and gold. i still cant buy it no matter what i try, emerald, diamond, and everything else work accept for that.

#### Server and plugin version
Spigot version: 1.17.1
BedWars version: SBA 1.5.0

**Comment by JustAHuman-xD** [comment] 2021-09-25 02:18
Sba doesn’t support 1.17.1 it’s not a bug, for issues like this go to the discord server. Also make sure you are using bedwars 0.2.18 not 0.2.19. If that’s all please close this

**Comment by zlataovce** [comment] 2021-09-25 07:36
not following the issue template, sba doesn't support 1.17.1

**Closed by zlataovce** 2021-09-25 07:36 UTC
Labels: bug
