### ISSUE TITLE
start game command

### ISSUE THREAD

**Issue by ARDragssss** [ScreamingSandals/BedWars#452] opened 2023-01-05 23:54 UTC
#### Describe the solution you'd like
i think adding a feature where u can execute a command when the game starts can be very useful. For example i have a replay plugin and i want to start recording when the game starts. If there is no end game command please add that too, if there is please tell me how.
#### Is your feature request related to a problem? Please describe
No

**Comment by TheHolyFire** [comment] 2023-03-07 12:33
Using the ScreamingSandals Bedwars API:
[StartEvent](https://jd.screamingsandals.org/sbw-0-2-x/BedWars-API/org/screamingsandals/bedwars/api/events/BedwarsGameStartedEvent.html)
[EndEvent](https://jd.screamingsandals.org/sbw-0-2-x/BedWars-API/org/screamingsandals/bedwars/api/events/BedwarsGameEndEvent.html)
Otherwise there is almost no way to make these Plugins cooperate with each other without creating a Plugin of your own...

**Comment by Misat11** [comment] 2024-06-21 19:44
Duplicate of #437

**Closed by Misat11** 2024-06-21 19:44 UTC
Labels: feature request
