### ISSUE TITLE
[Bug]: Internal Exeption io.netty.handler.codec.DecoderExpection /clientbound/minecraft:boss_event

### ISSUE THREAD

**Issue by Nerd10000** [ScreamingSandals/BedWars#551] opened 2024-10-29 15:20 UTC
### Bug description

When I kill someone the servr kicks me.

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/p/anonymous/85430ec82ae64793afaa302131b4596e

### Console log

No console log

### Additional information

[16:19:33 INFO]: Plugins (12): VoidGen, WorldEdit, ViaVersion, Vault, ServersNPC, Multiverse-Core, WorldGuard, BedWars, DeluxeHub, Essentials, EssentialsSpawn, EssentialsChat
Version: Paper 1.8.8

**Comment by Misat11** [comment] 2024-10-29 15:23
What client version do you use? Does it happen for 1.8 players as well or only for players on newer clients joining over Via*?

**Comment by Nerd10000** [comment] 2024-10-31 07:54
> What client version do you use? Does it happen for 1.8 players as well or only for players on newer clients joining over Via*?

I m using feather 1.21 but I tested with Prism launcher (cracked) 1.18 and same and liquidbounce with ViaFabric

**Comment by Nerd10000** [comment] 2024-10-31 08:15
It looks like it isn't working for 1.21+

**Comment by Nerd10000** [comment] 2024-10-31 08:16
I tested with 1.18 now and I didn't get the error but when I tpd to an arena I got kicked for Network Protocol Error

**Comment by blue-of-sky** [comment] 2024-11-17 11:38
I encountered this bug too. It's very annoying.

**Comment by Misat11** [comment] 2024-12-22 13:21
Sorry guys for the delay.

This has been caused by an undocumented change in ViaVersion 5.0.2 API, which we utilize to show colored BossBars to 1.9+ players on 1.8.8 servers. This has now been fixed in 0.2.36.1, and an option to disable this hook was also added in case a future version of Via* breaks it again.

**Closed by Misat11** 2024-12-22 13:21 UTC
Labels: bug, more information needed, 0.2.x
