### ISSUE TITLE
Scoreboard flicker

### ISSUE THREAD

**Issue by AMDBartek** [ScreamingSandals/BedWars#272] opened 2021-02-22 00:58 UTC
#### Describe the bug
The scoreboard flickers while waiting for a game to start, which does not occur while playing a game.
![2021-02-22_00 46 52](https://user-images.githubusercontent.com/46637209/108644672-eda05400-74a7-11eb-9601-aad1c0a3476d.png)
![2021-02-22_00 46 53](https://user-images.githubusercontent.com/46637209/108644676-f09b4480-74a7-11eb-8ac5-4f62499fb375.png)

#### Server and plugin version
Spigot version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
The Issue is not related to other plugins.

#### Console log
Nothing appears in the console

#### Configuration (of config.yml and shop.yml)
Not related to the shop.
config: https://paste.gg/p/anonymous/ea320fa8793b455899f9eb666a17913a

#### If there are problem with only one game, paste here config of this game
This happens in all games.

**Comment by Misat11** [comment] 2021-02-22 07:36
Duplicate of #251 and #59 
Fixed in snapshot versions of 0.3.0

**Closed by Misat11** 2021-02-22 07:36 UTC
Labels: bug

**Comment by AMDBartek** [comment] 2021-02-22 10:18
@Misat11 Will I need to use Java 11 for the snapshots?

**Comment by Misat11** [comment] 2021-02-22 10:20
For snapshots and future releases you will need Java 11. Same thing is comming for future versions of Paper and another server softwares.
https://docs.screamingsandals.org/Other/java11.html

**Comment by AMDBartek** [comment] 2021-02-22 10:30
@Misat11 will the snapshots run on a 1.12.2 server?
