### ISSUE TITLE
Dry run mode / Test mode

### ISSUE THREAD

**Issue by MinDBreaK** [ScreamingSandals/BedWars#295] opened 2021-04-05 22:07 UTC
#### Describe the solution you'd like
I would like the possibility to run an arena in dry mode. This would create the spawners, shops. It does not need to start anything else like timers.

Maybe if the spawners are spawning items, the shops could be really working so we can test everything. 

It would not count in statistics, but can have multiple players if they have the permissions to join a dry-run session. (by typing the same command for example)

It could be a command like `/bw admin <arena> dry-run` to keep the formating. 

#### Is your feature request related to a problem? Please describe
It is hard to debug shop configuration when working alone (late at night for example).

**Comment by pronze** [comment] 2021-04-15 20:20
Duplicate of issue #261

**Closed by pronze** 2021-04-15 20:20 UTC
Labels: feature request
