### ISSUE TITLE
[Feature]: Multiple prices on one item in a shop

### ISSUE THREAD

**Issue by hiyokochicken** [ScreamingSandals/BedWars#545] opened 2024-07-24 05:05 UTC
### Feature description

I would like to see a feature added that allows you to purchase items with multiple types of ore at the shop.
If it already exists, I would like to know how to do it.
For example, I would like to sell a diamond sword for 4 emeralds and 4 diamonds.
I'm Japanese and I'm not good at English, so I used Google Translate.
I'm sorry if the text is difficult to understand.
Thank you for reading.

**Comment by Misat11** [comment] 2024-12-22 14:29
Closing as a duplicate of #480

**Closed by Misat11** 2024-12-22 14:29 UTC
Labels: duplicate, feature request
