### ISSUE TITLE
GUI Editor, and therefore MMOItems and Mythic compatibility

### ISSUE THREAD

**Issue by IoIxD** [ScreamingSandals/BedWars#330] opened 2021-07-03 21:13 UTC
#### Describe the solution you'd like

A GUI editor for the shops, which would save every NBT tag for an item, allowing for easy support for custom items plugins like MythicMobs and MMOItems. 

#### Is your feature request related to a problem? Please describe
No, we'd just like to be able to add our own spice to the BedWars on our server, as we've done to survival and Spleef.

**Comment by AleesJaved** [comment] 2021-08-23 11:25
Same I want this too

**Comment by Misat11** [comment] 2024-06-21 19:34
Duplicate of #325

**Closed by Misat11** 2024-06-21 19:34 UTC
Labels: feature request
